-- Rooms and people are fixed demo fixtures (no administration), so their IDs are
-- assigned by the fixtures and stay stable across resets.
CREATE TABLE room (
    id        BIGINT       PRIMARY KEY,
    name      VARCHAR(80)  NOT NULL UNIQUE,
    location  VARCHAR(80)  NOT NULL,
    capacity  INT          NOT NULL CHECK (capacity > 0),
    equipment VARCHAR(255) NOT NULL -- comma-separated descriptive tags
);

CREATE TABLE person (
    id           BIGINT      PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL
);

-- Times are stored as UTC instants; the venue timezone is applied at the edges.
CREATE TABLE reservation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      BIGINT       NOT NULL REFERENCES room (id),
    person_id    BIGINT       NOT NULL REFERENCES person (id),
    title        VARCHAR(80)  NOT NULL,
    start_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    status       VARCHAR(16)  NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED')),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT reservation_start_before_end CHECK (start_at < end_at)
);

CREATE INDEX reservation_room_start ON reservation (room_id, start_at);
